---
 - name: Maintain OpenDistro Elastic Configuration
   hosts: localhost
   gather_facts: yes
   user: root
   vars_files:
     - group_vars/main.yml
     #- "vars/{{ Environment }}/main.yml"
   roles:
     - system
     - opendistro-elastic

   vars:
     lock_file_path: /tmp/ansible-playbook.lock

   pre_tasks:
       - name: Check if cluster is red
         uri: url=http://localhost:9200/_cluster/health method=GET
         register: red_cluster_health_response
         ignore_errors: True

       - name: Stop if cluster is red
         meta: end_host
         when: "red_cluster_health_response.json.status == 'red'"
         ignore_errors: True


       - name: register lock file
         stat: path={{lock_file_path}}
         register: lock_file

      - name: test for lock file  
        fail: msg="STOP  found a lockfile"
        when: lock_file.stat.exists|bool and not force_ignore_lock|bool

  # setup an override option
  #     - file: path={{lock_file_path}} state=absent
  #       sudo: yes
  #       when: "{{force_ignore_lock}}"

       - name: create lock file 
         file: path={{lock_file_path}} state=touch
         become: yes

       - name: Wait for cluster health to return to yellow or green
         uri: url=http://localhost:9200/_cluster/health method=GET
         register: cluster_health_response
         until: "cluster_health_response.json.status == 'yellow' or cluster_health_response.json.status == 'green'"
         retries: 500
         delay: 15
         ignore_errors: True  

   post_tasks:
       - file: path={{lock_file_path}} state=absent
         become: yes
