---
 - name: Maintain OpenDistro Elastic Configuration
   hosts: localhost
   gather_facts: yes
   user: root
   vars_files:
     - group_vars/main.yml
     #- "vars/{{ Environment }}/main.yml"
   roles:
     - system
    # - opendistro-elastic