---
 - name: Maintain OpenDistro Elastic Configuration
   hosts: localhost
   gather_facts: yes
   user: root
   vars_files:
     - group_vars/main.yml
     #- "vars/{{ Environment }}/main.yml"
   roles:
     - system
     - opendistro-elastic

   vars:
     lock_file_path: /tmp/ansible-playbook.lock

   pre_tasks: 
       - stat: path={{lock_file_path}}
         register: lock_file

       - fail: msg="Sorry, I found a lockfile, Add -f to your deploy command to forcefully continue deploying, if the previous deploy was aborted."
         when: lock_file.stat.exists|bool and not force_ignore_lock|bool

  #     - file: path={{lock_file_path}} state=absent
  #       sudo: yes
  #       when: "{{force_ignore_lock}}"

       - file: path={{lock_file_path}} state=touch
         become: yes

      
       - name: cluster health green
         uri: url=http://localhost:9200/_cluster/health method=GET
         register: cluster_health_response
         ignore_errors: True
        #  debug:
        #     msg: cluster health is {{ cluster_health_response.json.status}}
        #   until: "response.json.status == 'green'"
        #   retries: 500
        #   delay: 15

       - name: cluster status
         debug:
         msg: cluster health is {{ cluster_health_response.json.status}}
         ignore_errors: True

   post_tasks:
       - file: path={{lock_file_path}} state=absent
         become: yes
