---
 - name: Maintain OpenDistro Elastic Configuration
   hosts: localhost
   gather_facts: yes
   user: root
   vars_files:
     - group_vars/main.yml
     #- "vars/{{ Environment }}/main.yml"
   roles:
     - system
     - opendistro-elastic

   vars:
     lock_file_path: /tmp/ansible-playbook.lock

   pre_tasks: 
       - name: register lock file
         stat: path={{lock_file_path}}
         register: lock_file

       - name: test of lock file  
         fail: msg="Sorry, I found a lockfile, Add -f to your deploy command to forcefully continue deploying, if the previous deploy was aborted."
         when: lock_file.stat.exists|bool and not force_ignore_lock|bool

  #     - file: path={{lock_file_path}} state=absent
  #       sudo: yes
  #       when: "{{force_ignore_lock}}"

       - name: create lock file 
         file: path={{lock_file_path}} state=touch
         become: yes

       - name: Wait for cluster health to return to yellow or green
         uri: url=http://localhost:9200/_cluster/health method=GET
         register: cluster_health_response
         until: "cluster_health_response.json.status == 'yellow' or cluster_health_response.json.status == 'green'"
         retries: 500
         delay: 15
         ignore_errors: True  

   post_tasks:
       - file: path={{lock_file_path}} state=absent
         become: yes
