---
# tasks file for opendistro-elastic

# - name: configure elasticsearch hosts file
#   template:
#     src: templates/hosts.j2
#     dest: /etc/hosts
#     owner: root
#     group: root
#     mode: 0642
#   become: yes

#install common packages
- name: Install a list of packages
  apt:
    pkg:
    - zsh
    - nano
    - facter
    - awscli
    - jq

- name: configure resolv.conf file
  template:
    src: templates/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  become: yes

# - name: Update the /etc/hosts file with node name
#   tags: etchostsupdate
#     become: yes
#     become_user: root
#     lineinfile:
#         path: "/etc/hosts"
#         regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
#         line: "{{ hostvars[item]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
#         state: present
#         backup: yes
#       register: etchostsupdate
#       when: ansible_hostname != "{{ item }}" or ansible_hostname == "{{ item }}"
#       with_items: "{{groups['multi']}}"