---
# tasks file for opendistro-elastic
- name: configure elasticsearch hosts file
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0642
  become: yes

#install common packages
- name: Install a list of packages
  apt:
    pkg:
      - zsh
      - nano
      - facter
      - awscli
      - jq
      - mlocate

- name: configure resolv.conf file
  template:
    src: templates/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  become: yes
#######
# we use the admin group to grant sudo
- name: Ensure group "admin" exists
  group:
    name: admin
    state: present

###add jareking
- name: Add jareking
  user:
    name: jareking
    shell: /bin/bash
    groups: admin
    append: yes

###add public key
- name: add jareking ssh pubkey
  authorized_key:
    user: jareking
    state: present
    key: "{{ item }}"
  with_file:
    - public_keys/jareking

# NOTE: Fully quoted because of the ': ' on the line. See the Gotchas in the YAML docs.
- name: Validate the sudoers file before saving
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%ADMIN ALL="
    line: "%ADMIN ALL=(ALL) NOPASSWD: ALL"
    validate: /usr/sbin/visudo -cf %s
########

######
##sysctl
######

######
#max watched files
######

- sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
    sysctl_set: yes
    state: present
    reload: yes

######
# elasticseatch virtual memory
# https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
######
- sysctl:
    name: vm.max_map_count
    value: "262144"
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: fs.file-max
    value: "2000064"
    sysctl_set: yes
    state: present
    reload: yes

- sysctl:
    name: vm.max_map_count
    value: "200000"
    sysctl_set: yes
    state: present
    reload: yes
