---
# tasks file for opendistro-elastic

# - name: configure elasticsearch hosts file
#   template:
#     src: templates/hosts.j2
#     dest: /etc/hosts
#     owner: root
#     group: root
#     mode: 0642
#   become: yes

#install common packages
- name: Install a list of packages
  apt:
    pkg:
      - zsh
      - nano
      - facter
      - awscli
      - jq

- name: configure resolv.conf file
  template:
    src: templates/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  become: yes

###add jareking 
- name: Add jareking
  user:
    name: jareking
    shell: /bin/zsh
    #groups: admins
    append: yes

- name: add jareking ssh pubkey
  authorized_key:
    user: jareking
    state: present
    key: '{{ item }}'
  with_file:
    - public_keys/jareking  

########