---
# handlers file for elasticsearch

- name: elasticsearch restart bootstrap
  service: name=elasticsearch state=restarted
  become: yes
  when: 
    - openjdk_11_jdk_check_deb.rc == 1
    - elasticsearch_oss_check_deb.rc == 1